---
title: "Berkeley Police Stop Data Maps"
author: "Rebecca Reus"
date: "July 31, 2016"
output: 
  html_document:
    fig_width: 10
    fig_height: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(ggmap)
library(tidyr)
library(plyr)
library(dplyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(readr)
library(data.table)
library(rworldmap)
library(maps)
library(mapdata)
library(maptools)
library(scales)
library(RgoogleMaps)
#library(tmap)
library(sp)
library(rgdal)
library(rgeos)
library(RColorBrewer)
#library(raster)
#library(GISTools)
 #library(mgcv)
```

## Read in the Data:
```{r}
#finaldf <- readRDS( 'StopData_finaldf.rds' )
mergedf <- readRDS( 'StopData_merged.rds' )
```

## Location info:
```{r}
latmax <- max( mergedf$lat, na.rm = TRUE ) 
latmin <- min( mergedf$lat, na.rm = TRUE )
lonmax <- max( mergedf$long, na.rm = TRUE ) 
lonmin <- min( mergedf$long, na.rm = TRUE )
latvals <- c( latmin, latmax )
lonvals <- c( lonmin, lonmax )
```

## Make the variables factors:
```{r}
mergedf$CarSearch <- factor(mergedf$CarSearch)
levels(mergedf$CarSearch) <- c("No Search", "Search")  

mergedf$Race <- factor(mergedf$Race)
levels(mergedf$Race) <- c("Asian", "Black", "Hispanic", "Other", "White")

mergedf$Enforcement <- factor(mergedf$Enforcement)
levels(mergedf$Enforcement) <- c("Arrest", "Citation", "Other", "Warning")

mergedf$Reason <- factor(mergedf$Reason)
levels(mergedf$Reason) <- c("Other", "Investigation", "Probation/Parole", "Reasonable Suscipcion", "Traffic", "Wanted")

mergedf <- mergedf %>%
  mutate(Arrest = ifelse( 
    as.character(Enforcement) == "Arrest", 
    "Arrested",
    "Not Arrested") ) %>%
  mutate(Arrest = factor(Arrest))

v <- factor(mergedf$Other)
levels(v)

mergedf <- mergedf %>%
  mutate(Emergency.Psych.Eval = ifelse( str_detect(as.character(Other), "MH"), 
                                        yes = "Yes",
                                        no = "No") )

mergedf$Emergency.Psych.Eval <- factor(mergedf$Emergency.Psych.Eval)

```

## Map 1
```{r}
newmap <- getMap( resolution="low" )
plot( newmap, xlim = lonvals, ylim = latvals, asp=1 )
points( mergedf$long, mergedf$lat, col="red", cex=.6 )
```

## Map 2
```{r}

berkMap = map = get_map(location = c( lon = mean(lonvals), lat = mean(latvals) ), zoom = 14)
ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, color = Incident.Type), data = mergedf, alpha = 0.2, size = 3) + 
  scale_colour_discrete( "Incident Type", labels = c("Pedestrian Stop", "Bicycle Stop", "Suspicious Vehicle Stop",  "Traffic Stop" ) ) +
  theme ( 
		#legend.position = c(0.05, 0.05), # put the legend INSIDE the plot area
		#legend.justification = c(0, 0),
		#legend.background = element_rect(colour = F, fill = "white"),
		#legend.key = element_rect (fill = F, colour = F),
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + 
  ggtitle("All BPD Stops by Incident Type, 2015-2016") 
```

## MAP 2.1
```{r}
ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, size = CarSearch, color = Race), data = mergedf, alpha = 0.2) + 
  scale_size_discrete( "Car Search", labels = c("No Search", "Search") ) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + 
  ggtitle("BPD All Stops w/ Car Searches by Race 2015-2016") +
  facet_wrap(~ Race, ncol = 3 ) 
```


## MAP 2.2
```{r}
df <- subset(mergedf, as.character(Enforcement) == "Arrest")

ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, colour = Race), data = df, alpha = 0.5, size = 5) + 
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + 
  ggtitle("BPD Stops to Arrests, by Race 2015-2016") +
  facet_wrap(~ Race) 
```

## MAP 2.3
```{r}
ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, colour = Race, size = Arrest), data = mergedf, alpha = 0.5)  + 
  scale_size_discrete( range = c(7, 3) ) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + 
  ggtitle("BPD Stops to Arrests, by Race 2015-2016") +
  facet_wrap(~ Race)

# p <- sum(as.character(mergedf$Arrest) == "Arrested")/nrow(Arrest)
# 
# print( str_c( Percent of People Arrested Out of Total People Stopped: ), )
```


## MAP 2.4
```{r}

df <- subset(mergedf, as.character(Emergency.Psych.Eval) == "Yes")

ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, colour = Race), data = df, alpha = 0.5, size = 6) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + 
  ggtitle("BPD Stops with Emergency Psch Evaluation, by Race 2015-2016") 

```

## MAP 3:
```{r}
ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, colour = factor(Gender)), data = mergedf, alpha = 0.2, size = 3) + 
  scale_colour_discrete( "Gender", labels = c("Female", "Male") ) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + 
  ggtitle("All BPD Stops by Gender, 2015-2016") 
```

## MAP 4:
```{r}
ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, colour = Reason), data = mergedf, alpha = 0.7, size = 3) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + ggtitle("All BPD Stops, by Reason 2015-2016") +
    facet_wrap( ~ Reason , ncol = 2)
```

## MAP 4.1
```{r}
df <- subset(mergedf, as.character(Reason) == "Traffic")

ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, colour = Race, size= Arrest), data = df, alpha = 0.5) + 
  scale_size_discrete( range = c(5, 2) ) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + 
  ggtitle("BPD Traffic Stops Only, by Race 2015-2016") +
  facet_grid(~ Race)
```

## MAP 5:
```{r}
# doing it with qmplot is even easier
qmplot(long, lat, data = mergedf, maptype = "toner-lite",
  color = factor(Race), size = factor(CarSearch), legend = "topleft"
) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + ggtitle("BPD Stops 2015-2016")  + 
  scale_colour_discrete( "Race", labels = c("Asian", "Black", "Hispanic", "Other", "White")  ) +
  scale_size_discrete("Car Search", labels = c("No Search", "Search"))
```

## MAP 6:
```{r}
ggmap(berkMap) +
  geom_point( data = mergedf, aes(x = long, y = lat, colour = factor(Race), size = factor(CarSearch) ), alpha = 0.5 ) + 
  scale_colour_discrete( "Race", labels = c("Asian", "Black", "Hispanic", "Other", "White")  ) +
  scale_size_discrete("CarSearch", labels = c("No Search", "Search"),
     range = c(1.75,6)) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + ggtitle("BPD Stops by Race and Car Search 2015-2016") +
  labs(size = "CarSearch")
```

## MAP 6.1:
```{r}
# a contour plot
ggmap(berkMap) +
  stat_density2d(aes(x = long, y = lat, fill= ..level.., alpha = .2* ..level..),
    size = 2, bins = 5, data = mergedf, geom = "polygon") +
  scale_fill_gradient(low = "black", high = "red") +
    theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + ggtitle("All BPD Stops Density, 2015-2016") +
  labs(alpha = element_blank())
```

## MAP 6.2
```{r}
qmplot(long, lat, data = mergedf) +
  ggtitle("All BPD Stops")
qmplot(long, lat, data = mergedf, facets = ~ Race) +
  ggtitle("All BPD Stops by Race")
```


## MAP 7
```{r, fig.height = 25, fig.width = 5}
# crime example by month
mergedf <- mergedf %>%
 # mutate( Call.Date.Time = mdy_hm( as.character(Call.Date.Time) ) ) %>%
 # mutate( Call.Hour = hour( as.character(Call.Date.Time) ) ) %>%
  #mutate( Call.Date = mdy( as.character(Call.Date.Time) ) ) %>%
  mutate( Call.Month = month( mdy_hm(Call.Date.Time) ) ) #%>%
 # mutate( Call.Weekday = wday( as.character(Call.Date.Time) ) )
mergedf$Call.Month <- factor(mergedf$Call.Month)

map7 <- get_map(location = "berkeley", zoom = 14, source = "osm", color = "bw")
BerkMap7 <- ggmap( map7,
  base_layer = ggplot(aes(x = long, y = lat), data = mergedf))
```

```{r}
BerkMap7 +
  stat_density2d( aes(x = long, y = lat, fill = ..level.., alpha = ..level..),
    bins = I(5), geom = "polygon", data = mergedf ) +
  scale_fill_gradient2( "StopDensity",
    low = "white", mid = "orange", high = "red", midpoint = 500) +
  labs(x = "Longitude", y = "Latitude") + facet_wrap(~ Call.Month, ncol = 6) +
  scale_alpha(range = c(.2, .55), guide = FALSE) +
  ggtitle("BPD Stop Contour Map of Berkeley by Month") +
  guides(fill = guide_colorbar(barwidth = 1.5, barheight = 10))
```


## MAP 8
# ```{r}
# # crime density by race:
# mergedf <- mergedf %>%
#  # mutate( Call.Date.Time = mdy_hm( as.character(Call.Date.Time) ) ) %>%
#  # mutate( Call.Hour = hour( as.character(Call.Date.Time) ) ) %>%
#   #mutate( Call.Date = mdy( as.character(Call.Date.Time) ) ) %>%
#   mutate( Call.Month = month( mdy_hm(Call.Date.Time) ) ) #%>%
#  # mutate( Call.Weekday = wday( as.character(Call.Date.Time) ) )
# mergedf$Call.Month <- factor(mergedf$Call.Month)
# 
# map7 <- get_map(location = "berkeley", zoom = 6, source = "osm", color = "bw")
# BerkMap7 <- ggmap( map7,
#   base_layer = ggplot(aes(x = long, y = lat), data = mergedf))
# 
# BerkMap7 +
#   stat_density2d( aes(x = long, y = lat, fill = ..level.., alpha = ..level..),
#     bins = I(5), geom = "polygon", data = mergedf ) +
#   scale_fill_gradient2( "StopDensity",
#     low = "white", mid = "orange", high = "red", midpoint = 500) +
#   labs(x = "Longitude", y = "Latitude") + facet_wrap(~ Race ) +
#   scale_alpha(range = c(.2, .55), guide = FALSE) +
#   ggtitle("BPD Stop Contour Map of Berkeley by Race") +
#   guides(fill = guide_colorbar(barwidth = 1.5, barheight = 10))
# ```

## MAP 9
```{r}
ggmap(berkMap) +
  stat_density2d( aes(x = long, y = lat, fill = ..level.., alpha = ..level..),
    bins = I(5), geom = "polygon", data = mergedf ) +
  scale_fill_gradient2( "StopDensity",
    low = "white", mid = "orange", high = "red", midpoint = 100) +
  labs(x = "Longitude", y = "Latitude") + facet_wrap( ~ Race ) +
  scale_alpha(range = c(.2, .55), guide = FALSE) +
  ggtitle("BPD Stop Contour Map of Berkeley by Race") +
  guides(fill = guide_colorbar(barwidth = 1.5, barheight = 10))
```

## MAP 10 : AgeRange Density Facet
```{r}
ggmap(berkMap) +
  stat_density2d( aes(x = long, y = lat, fill = ..level.., alpha = ..level..),
    bins = I(5), geom = "polygon", data = mergedf ) +
  scale_fill_gradient2( "Stop Density",
    low = "white", mid = "orange", high = "red", midpoint = 25) +
  labs(x = "Longitude", y = "Latitude") + facet_wrap(~ AgeRange) +
  scale_alpha(range = c(.2, .55), guide = FALSE) +
  ggtitle("BPD Stop Contour Map of Berkeley by Age Range") +
  guides(fill = guide_colorbar(barwidth = 1.5, barheight = 10))
```

## MAP 11: By Race Again
```{r}
# ggmap(berkMap) +
# geom_point(aes(x = long, y = lat, colour = Race, size = Race),
#   data = mergedf)

ggmap(berkMap) +
stat_bin2d(
aes(x = long, y = lat, colour = Race, fill = Race),
size = .25, bins = 100, alpha = .25,
data = mergedf
)

```

```{r}
ggmap(berkMap) +
stat_density2d(aes(x = long, y = lat, fill = ..level.., alpha = ..level..),
bins = 5, geom = "polygon",
data = mergedf ) +
scale_fill_gradient(low = "black", high = "red")
```

# Get Shapefiles
```{r}
#locationCensusFiles <- "C:/Users/Rebecca/Dropbox/School/2016_su_School/stat133/finalproject_angry_ladies/Rebeccas_location_Code2/Census_Block_Group_Polygons2010"
blocks <- readOGR("Census_Block_Group_Polygons2010","Census_blockgroups_2010", verbose = TRUE)

blocks.polygons <- blocks@polygons
blocks.data <- blocks@data
blocks.plot.order <- blocks@plotOrder
b2 <- spTransform(blocks, CRS("+proj=longlat +datum=WGS84"))
b3 <- fortify(b2)
```

## Map 12
```{r}
bMap12 <- ggmap(berkMap) + 
  geom_polygon(aes(x=long, y=lat, group=group), fill='grey', size=1,color='red', data=b3, alpha=0) +
  geom_point( data = mergedf, aes(x = long, y = lat), alpha = 0.2, size = 3 )
bMap12
```


## MAP 13
```{r}
bMap12 <- ggmap(berkMap) + 
geom_polygon(aes(x = long, y = lat, group = group), data = b3,
               colour = 'white', fill = 'black', alpha = .4, size = .3) +
  geom_point( data = mergedf, aes(x = long, y = lat), alpha = 0.2, size = 3, color = 'red' )
bMap12

```

# Get Shapefiles Again
```{r}
locationCensusFiles <- "C:/Users/Rebecca/Dropbox/School/2016_su_School/stat133/finalproject_angry_ladies/Rebeccas_location_Code2/Census_Tract_Polygons2010"

locationCensusFiles <- "Census_Tract_Polygons2010"
blocks <- readOGR("Census_Tract_Polygons2010","Census_tracts_2010", verbose = TRUE)

locationCensusFiles <- "Census_Tract_Polygons2010"
blocks <- readOGR(locationCensusFiles,"Census_tracts_2010", verbose = TRUE)
summary(blocks)
print(proj4string(blocks))
# blocks.polygons <- blocks@polygons
# blocks.data <- blocks@data
# blocks.plot.order <- blocks@plotOrder
b2 <- spTransform(blocks, CRS("+proj=longlat +datum=WGS84"))
b3 <- fortify(b2)
```

## Map 14
```{r}
bMap12 <- ggmap(berkMap) + 
geom_polygon(aes(x = long, y = lat, group = group), data = b3,
               colour = 'black', fill = 'white', alpha = .4, size = .3) +
  geom_point( data = mergedf, aes(x = long, y = lat), alpha = 0.2, size = 3, color = 'red' )
bMap12
```

## Population by census block group:
```{r}
shpfile <- "Census_tracts_2010.shp"
sh <- readShapePoly("Census_Tract_Polygons2010/Census_tracts_2010.shp")
#plot(sh)
sh@data$ID <- as.numeric(sh@data$ID)

# Read in the demographic data and merge on Neighbourhood Id
demo <- read.csv(file="Census_tracts_2010.csv", header = TRUE)
sh2 <- merge(sh, demo, by='ID')

# Set the palette
p <- colorRampPalette(c("white", "red"))(128)
palette(p)

# Scale the total population to the palette
pop <- sh2@data$TotalPop.x
#str(sh2)
#sh2[1]
#sh2@data$TotalPop.x
#pop <- c(2925,3144,4196,4658,3558,3387,2007,3198,3563,1992,1756,3632,3118,3844,3716,3647,3640,8368,3633,5659,2642,2794,1593,2685,1552,2020,2172,3964,4396,4885,1215,4336,4685)

cols <- (pop - min(pop))/diff(range(pop))*127+1
plot(sh, col=cols)
#points( mergedf$long, mergedf$lat, col="black", cex=.6 )



```


<!-- # Map 15 -->
<!-- ```{r} -->
<!-- sh2data <- sh2@data -->
<!-- j <- merge( sh2data, demo, by.x= "GEOID10.x", by.y="GEOID10"  ) -->

<!-- # Plot -->
<!-- bMap12 <- ggmap(berkMap) + -->
<!--   geom_polygon(aes(x=long,y=lat, group=group, fill=TotalPop), data=sh2, color='white') + -->
<!--   scale_fill_gradient(low='white', high='orange') + -->
<!--   geom_point( data = mergedf, aes(x = long, y = lat), alpha = 0.2, size = 3, color = 'red' ) -->
<!-- bMap12 -->
<!-- ``` -->



